{
 "title": "Desafio 05 - Jornada",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nodejs Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_version_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "TOTAL - Requisições HTTP - GET",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{app=\"web\"}) by(method,path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "TOTAL - Requisições HTTP - GET",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_total{app=\"web\"}) by(method,path)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Aplicação is UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{app=\"web\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodejs - HEAP Memory - Size Total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NodeJs - HEAP Memory - Size Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System - Total CPU TIme",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_system_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User - Total CPU TIme",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_user_seconds_total", "legendFormat": "__auto" }
   ]
  }
 ]
}