apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-conversao-temp
spec:
  selector:
    matchLabels:
      app: conversao-temp
  template:   
    metadata:
      labels:
        app: conversao-temp
    spec:
      containers:
        - name: conversao-temp
          image: coliveiraa/desafio-01-conversao-temperatura:{{TAG}}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-deploy-conversao-temp
spec:
  selector:
    app: conversao-temp
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 30800
  type: LoadBalancer