pipeline {
    agent any

    stages {

        stage ('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("coliveiraa/desafio-04-kubenews:${env.BUILD_ID}", '-f desafio-04/Dockerfile desafio-02/kube-news/src')
                }
            }
        }

    }
}