pipeline {
    agent any

    stages {

        stage ('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("coliveiraa/desafio-04-kubenews:RC-${env.BUILD_ID}", '-f desafio-04/Dockerfile desafio-04/kube-news/src')
                }
            }            
        }

        stage ('Push Kube-News Image do DockerHub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'usr_pwd_docker_hub') {
                        dockerapp.push('latest')
                        dockerapp.push("RC-${env.BUILD_ID}")
                    }
                }                
            }
        }

        stage ('Deploy do Kube-News no K8S') {
            environment {
                tag_version = "RC-${env.BUILD_ID}"
            }            
            steps {
                withKubeConfig([credentialsID: 'config-cluster-do']) {                    
                    sh 'sed -i "s/{{TAG}}/$tag_version/g" desafio-04/deploy-conversao-temperatura.yaml'
                    sh 'kubectl apply -f desafio-04/deploy-conversao-temperatura.yaml'
                }
            }
        }

    }
}